Repository cowaine/spring-boot-for-msa, pull requests merged in 2023-08, with the labels that each got.

#20 Feature/joisfe
  .idea/ChatGPTCopilotChannelManager.xml
  joisfe/src/main/java/com/cowaine/joisfe/JoisfeApplication.java
  joisfe/src/main/java/com/cowaine/joisfe/part3/DateFormatter.java
  joisfe/src/main/java/com/cowaine/joisfe/part3/Formatter.java
  joisfe/src/main/java/com/cowaine/joisfe/part3/LifeCycleComponent.java
  joisfe/src/main/java/com/cowaine/joisfe/part3/LocalDateTimeFormatter.java
  joisfe/src/main/java/com/cowaine/joisfe/part3/PriceUnit.java
  joisfe/src/main/java/com/cowaine/joisfe/part3/PrintableBeanPostProcessor.java
Labels: chapter03

#26 Feature/youngju jang
  youngju-jang/src/main/java/com/cowaine/youngjujang/YoungjuJangApplication.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/config/MailConfig.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/config/ServerConfig.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/config/ServerConfiguration.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/config/ThreadPoolConfig.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/domain/DateFormatter.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/domain/Formatter.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/domain/LifeCycleComponent.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/domain/LifeCycleComponentVer2.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/domain/LocalDateTimeFormatter.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/domain/Money.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/domain/PriceUnit.java
  youngju-jang/src/main/java/com/cowaine/youngjujang/ch2_3/domain/PrintableBeanPostProcessor.java
  youngju-jang/src/main/resources/application.yaml
Labels: chapter02, chapter03

#27 Feature/ding-cook
  ding-cook/src/main/java/com/cowaine/dingcook/DingCookApplication.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex01/PriceUnit.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex01/SpringBean01Application.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex02/Formatter.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex02/LocalDateTimeFormatter.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex02/SpringBean02Application.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex03/OrderPrinter.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex03/ProductOrder.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex05/DateFormatter.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex05/SpringBean05Application.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex06/LifeCycleComponent.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex06/PrintBeanPostProcessor.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex06/SpringBean06Application.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex07/SpringBean08Application.java
  ding-cook/src/main/java/com/cowaine/dingcook/domain/ex09/SpringBean09Application.java
  ding-cook/src/main/resources/application.yaml
Labels: chapter03

#30 Feature/corock
  corock/src/main/java/com/cowaine/corock/CorockApplication.java
  corock/src/main/java/com/cowaine/corock/chapter03/advanced/SystemConfig1.java
  corock/src/main/java/com/cowaine/corock/chapter03/advanced/SystemConfig2.java
  corock/src/main/java/com/cowaine/corock/chapter03/circularreference/CircularReference.java
  corock/src/main/java/com/cowaine/corock/chapter03/circularreference/CircularService.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/AppPushSender.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/DateFormatter.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/DividePatternConfig.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/DivideServerConfig.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/Formatter.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/LocalDateTimeFormatter.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/NotificationService.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/OrderPrinter.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/OrderProduct.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/Printer.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/Sender.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/ServerConfig.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/SmsSender.java
  corock/src/main/java/com/cowaine/corock/chapter03/di/User.java
  corock/src/main/java/com/cowaine/corock/chapter03/domain/Money.java
  corock/src/main/java/com/cowaine/corock/chapter03/domain/PriceUnit.java
  corock/src/main/java/com/cowaine/corock/chapter03/lifecycle/LifeCycleComponent.java
  corock/src/main/java/com/cowaine/corock/chapter03/lifecycle/PrintableBeanPostProcessor.java
  corock/src/main/java/com/cowaine/corock/chapter04/controller/ApiController.java
  corock/src/main/java/com/cowaine/corock/chapter04/domain/Hotel.java
  corock/src/main/java/com/cowaine/corock/chapter04/domain/HotelSearchService.java
  corock/src/main/resources/application.yaml
Labels: chapter03, chapter04
